script: phantomjs test/runner.js test/index.html
notifications:
  on_success: change
  on_failure: always
  hipchat:
    rooms:
      # Content tools
      secure: NY8epJEsjkNdqjWkukMSKeKgwPQSBT4/jjihPSRXFV0g5r2h0GrpGnh29pd3iyDVuW4V0+yga5Af3olqJF0mjMfFr8lurWnAvqaJIdJYmqsiMlx25B3PJyPUQ+OvE6QH/EOlGlgVONJJBRz2AFeOgIpWGnD5ckTeSbu2LD/DuIk=
